openapi: 3.0.0
info:
  title: PoC API
  version: 1.0.0
paths: {}
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique ID of the user
        username:
          type: string
          description: User's chosen username
        active:
          type: boolean
          description: Account active status